title: Geometric
description: Evolutionary algorithms for optimised CUDA kernels
url: https://geometricagi.github.io
markdown: kramdown

author:
  name: Jack Foxabbott
  title: Founding Member of Technical Staff
  linkedin: https://www.linkedin.com/in/foxabbott/
